# Generated by Django 4.1.6 on 2024-03-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('anio', models.IntegerField()),
                ('url_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('descripcion', models.TextField(max_length=500)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='moviebackapp.genero')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.CharField(max_length=250)),
                ('peliculas_vistas', models.ManyToManyField(to='moviebackapp.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('peliculas', models.ManyToManyField(to='moviebackapp.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=45)),
                ('esVieja', models.BooleanField()),
                ('esPopular', models.BooleanField()),
                ('recibioPremios', models.BooleanField()),
                ('pelicula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moviebackapp.pelicula')),
            ],
        ),
    ]
